image: node:10.15.3

stages:
  - install_dependencies
  - build
  # - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm i
  only:
    changes:
      - package.json
      

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

deploy as review app:
  image: rambabusaravanan/firebase
  stage: deploy
  only:
    - master
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://oalmilktea.web.app
  script:
    - firebase use oalmilktea --token $FIREBASE_TOKEN
    - firebase target:apply hosting user oalmilktea
    - firebase deploy --only hosting -m "tata" --token $FIREBASE_TOKEN